### ISSUE TITLE
IllegalArgumentException: Argument for @NotNull parameter 'library' of com/intellij/openapi/roots/impl/RootModelImpl.addLib...

### ISSUE THREAD

**Issue by kshchepanovskyi** [protostuff/protobuf-jetbrains-plugin#114]
https://sentry.io/ks-projects/protobuf-support/issues/696375283/

```
IllegalArgumentException: Argument for @NotNull parameter 'library' of com/intellij/openapi/roots/impl/RootModelImpl.addLibraryEntry must not be null
    at com.intellij.openapi.roots.impl.RootModelImpl.$$$reportNull$$$0(RootModelImpl.java)
    at com.intellij.openapi.roots.impl.RootModelImpl.addLibraryEntry(RootModelImpl.java)
    at io.protostuff.jetbrains.plugin.ProtostuffPluginController.lambda$addLibrary$1(ProtostuffPluginController.java:130)
    at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:1038)
    at io.protostuff.jetbrains.plugin.ProtostuffPluginController.addLibrary(ProtostuffPluginController.java:129)
...
(87 additional frame(s) were not displayed)
```

**Comment by kshchepanovskyi** [comment]
This issue is closed as plugin is not supported anymore. 
Please switch to https://github.com/jvolkman/intellij-protobuf-editor.
