### ISSUE TITLE
IllegalStateException: Could not find protobuf sources jar

### ISSUE THREAD

**Issue by kshchepanovskyi** [protostuff/protobuf-jetbrains-plugin#115]
https://sentry.io/ks-projects/protobuf-support/issues/696371621/

```
IllegalStateException: Could not find protobuf sources jar
    at io.protostuff.jetbrains.plugin.reference.file.BundledProtobufRootsProvider.getSourceRoots(BundledProtobufRootsProvider.java:42)
    at io.protostuff.jetbrains.plugin.ProtostuffPluginController.updateGlobalLibrary(ProtostuffPluginController.java:138)
    at io.protostuff.jetbrains.plugin.ProtostuffPluginController.projectOpened(ProtostuffPluginController.java:87)
    at com.intellij.openapi.project.impl.ProjectManagerImpl.fireProjectOpened(ProjectManagerImpl.java:781)
    at com.intellij.openapi.project.impl.ProjectManagerImpl.lambda$null$6(ProjectManagerImpl.java:390)
...
(57 additional frame(s) were not displayed)

Could not update global protobuf library bundle
```

**Comment by deadwind4** [comment]
me too
