### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by kshchepanovskyi** [protostuff/protobuf-jetbrains-plugin#116]
https://sentry.io/ks-projects/protobuf-support/issues/706031040/

```
NullPointerException: None
    at org.antlr.jetbrains.adapter.SymtabUtils.getContextFor(SymtabUtils.java:54)
    at org.antlr.jetbrains.adapter.psi.AntlrPsiNode.getContext(AntlrPsiNode.java:58)
    at org.antlr.jetbrains.adapter.psi.AntlrPsiNode.getContext(AntlrPsiNode.java:32)
    at com.gmail.blueboxware.libgdxplugin.filetypes.skin.refactoring.ChangeKotlinPackageListener.childReplaced(ChangeKotlinPackageListener.kt:52)
    at com.intellij.psi.impl.PsiManagerImpl.fireEvent(PsiManagerImpl.java:432)
...
(55 additional frame(s) were not displayed)
```

**Comment by kshchepanovskyi** [comment]
This issue is closed as plugin is not supported anymore. 
Please switch to https://github.com/jvolkman/intellij-protobuf-editor.
