### ISSUE TITLE
AssertionError: Invalid libraryOrderEntry, library: Library: name:Bundled Protobuf Distribution; roots:[VFPContai...

### ISSUE THREAD

**Issue by kshchepanovskyi** [protostuff/protobuf-jetbrains-plugin#118]
https://sentry.io/ks-projects/protobuf-support/issues/723042495/

```
AssertionError: Invalid libraryOrderEntry, library: Library: name:Bundled Protobuf Distribution; roots:[VFPContainer: [], VFPContainer: [], VFPContainer: [], VFPContainer: [], VFPContainer: []] of type class com.intellij.openapi.roots.impl.libraries.LibraryImpl, disposed: true, kind: null
    at com.intellij.openapi.roots.impl.RootModelImpl.addLibraryEntry(RootModelImpl.java:268)
    at io.protostuff.jetbrains.plugin.ProtostuffPluginController.lambda$addLibrary$1(ProtostuffPluginController.java:130)
    at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:1038)
    at io.protostuff.jetbrains.plugin.ProtostuffPluginController.addLibrary(ProtostuffPluginController.java:129)
    at io.protostuff.jetbrains.plugin.ProtostuffPluginController$1.fileOpenedSync(ProtostuffPluginController.java:107)
...
(84 additional frame(s) were not displayed)
```

**Comment by kshchepanovskyi** [comment]
This issue is closed as plugin is not supported anymore. 
Please switch to https://github.com/jvolkman/intellij-protobuf-editor.
