### ISSUE TITLE
BUILD FAILED

### ISSUE THREAD

**Issue by jlovedragon** [protostuff/protobuf-jetbrains-plugin#43]
`./gradlew build`
Cannot find PsiViewer:3.28.93

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'protobuf-jetbrains-plugin'.
> Cannot find plugin PsiViewer:3.28.93 at http://plugins.jetbrains.com

```
./gradlew build --debug
13:27:45.063 [INFO] [org.jetbrains.intellij.IntelliJPlugin] Configuring IntelliJ plugin PsiViewer:3.28.93
13:27:45.063 [INFO] [org.jetbrains.intellij.IntelliJPlugin] Downloading PsiViewer:3.28.93 from http://plugins.jetbrains.com
13:27:45.064 [INFO] [plugin-repository-rest-client] Downloading PsiViewer:3.28.93
13:27:45.065 [DEBUG] [plugin-repository-rest-client] ---> HTTP GET http://plugins.jetbrains.com/plugin/download?pluginId=PsiViewer&version=3.28.93
13:27:45.489 [DEBUG] [sun.net.www.protocol.http.HttpURLConnection] sun.net.www.MessageHeader@1e09f1dc5 pairs: {GET /plugin/download?pluginId=PsiViewer&version=3.28.93 HTTP/1.1: null}{User-Agent: Java/1.8.0_111}{Host: plugins.jetbrains.com}{Accept: text/html, image/gif, image/jpeg, *; q=.2, */*; q=.2}{Connection: keep-alive}
13:27:45.766 [DEBUG] [sun.net.www.protocol.http.HttpURLConnection] sun.net.www.MessageHeader@5acc28f10 pairs: {null: HTTP/1.1 302}{Server: nginx}{Date: Wed, 19 Apr 2017 05:27:45 GMT}{Content-Length: 0}{Connection: keep-alive}{Set-Cookie: ccc=duqe5b;Max-Age=157680000;Expires=Mon, 18-Apr-2022 05:27:45 GMT}{Location: http://plugins.jetbrains.com/files/227/31087/PsiViewer.jar}{X-Frame-Options: DENY}{X-Content-Type-Options: nosniff}{X-XSS-Protection: 1; mode=block;}
13:27:45.767 [DEBUG] [plugin-repository-rest-client] <--- HTTP 302 http://plugins.jetbrains.com/plugin/download?pluginId=PsiViewer&version=3.28.93 (702ms)
13:27:45.768 [DEBUG] [sun.net.www.protocol.http.HttpURLConnection] sun.net.www.MessageHeader@4ca13e215 pairs: {GET /files/227/31087/PsiViewer.jar HTTP/1.1: null}{User-Agent: Java/1.8.0_111}{Host: plugins.jetbrains.com}{Accept: text/html, image/gif, image/jpeg, *; q=.2, */*; q=.2}{Connection: keep-alive}
13:27:46.005 [DEBUG] [sun.net.www.protocol.http.HttpURLConnection] sun.net.www.MessageHeader@97e219810 pairs: {null: HTTP/1.1 302 Moved Temporarily}{Server: nginx}{Date: Wed, 19 Apr 2017 05:27:45 GMT}{Content-Type: text/html}{Content-Length: 154}{Connection: keep-alive}{Location: http://jetbrains-plugins.s3.amazonaws.com/227/31087/PsiViewer.jar}{X-Frame-Options: DENY}{X-Content-Type-Options: nosniff}{X-XSS-Protection: 1; mode=block;}
13:27:46.006 [DEBUG] [sun.net.www.protocol.http.HttpURLConnection] Redirected from http://plugins.jetbrains.com/files/227/31087/PsiViewer.jar to http://jetbrains-plugins.s3.amazonaws.com/227/31087/PsiViewer.jar
13:27:46.333 [DEBUG] [sun.net.www.protocol.http.HttpURLConnection] sun.net.www.MessageHeader@4ca13e215 pairs: {GET /227/31087/PsiViewer.jar HTTP/1.1: null}{User-Agent: Java/1.8.0_111}{Host: jetbrains-plugins.s3.amazonaws.com}{Accept: text/html, image/gif, image/jpeg, *; q=.2, */*; q=.2}{Connection: keep-alive}
13:27:46.637 [DEBUG] [sun.net.www.protocol.http.HttpURLConnection] sun.net.www.MessageHeader@58a8a67a11 pairs: {null: HTTP/1.1 200 OK}{x-amz-id-2: 4o9lTFfbuh0euV18jM1dZoxRlsiFArCrd9kj38JIe4gUpEPqi70BLxWIgp5Qqxr3/k9ppnQrUSE=}{x-amz-request-id: CDBDBDC9F3AFD558}{Date: Wed, 19 Apr 2017 05:27:47 GMT}{Last-Modified: Wed, 12 Apr 2017 21:39:47 GMT}{ETag: "c7dc518b90e85b31794fd1c56bc0e981"}{x-amz-version-id: QIwSSKe7USVv2IZc5tCwRT0.3cw2XYk4}{Accept-Ranges: bytes}{Content-Type: application/x-java-archive}{Content-Length: 94353}{Server: AmazonS3}
13:27:46.637 [ERROR] [plugin-repository-rest-client] Cannot find PsiViewer:3.28.93
13:27:46.638 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]
13:27:46.638 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] FAILURE: Build failed with an exception.
13:27:46.639 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]
13:27:46.639 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * What went wrong:
13:27:46.639 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] A problem occurred configuring root project 'protobuf-jetbrains-plugin'.
13:27:46.639 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] > Cannot find plugin PsiViewer:3.28.93 at http://plugins.jetbrains.com
```

but i can get the plugin from chrome after i type the website[http://plugins.jetbrains.com/plugin/download?pluginId=PsiViewer&version=3.28.93]

**Comment by kshchepanovskyi** [comment]
It is weird, maybe some temporary issue. 
There is a workaround - you can comment line containing `PsiViewer` in [build.gradle](https://github.com/protostuff/protobuf-jetbrains-plugin/blob/master/build.gradle) - this plugin does not affect build, it is used only for convenience when you run `./gradlew runIde`.

**Comment by kshchepanovskyi** [comment]
Reproduced on one of my machines (Windows 10 x64):

```
11:09:16.413 [INFO] [org.jetbrains.intellij.IntelliJPlugin] IntelliJ IDEA IC-171.3780.107 is used for building
11:09:16.414 [INFO] [org.jetbrains.intellij.IntelliJPlugin] Configuring IntelliJ IDEA plugin dependencies
11:09:16.415 [INFO] [org.jetbrains.intellij.IntelliJPlugin] Configuring IntelliJ plugin PsiViewer:3.28.93
11:09:16.415 [INFO] [org.jetbrains.intellij.IntelliJPlugin] Downloading PsiViewer:3.28.93 from http://plugins.jetbrains.com
11:09:16.416 [INFO] [plugin-repository-rest-client] Downloading PsiViewer:3.28.93
11:09:16.416 [DEBUG] [plugin-repository-rest-client] ---> HTTP GET http://plugins.jetbrains.com/plugin/download?pluginId=PsiViewer&version=3.28.93
11:09:16.458 [DEBUG] [sun.net.www.protocol.http.HttpURLConnection] sun.net.www.MessageHeader@d0a33145 pairs: {GET /plugin/download?pluginId=PsiViewer&version=3.28.93 HTTP/1.1: null}{User-Agent: Java/1.8.0_121}{Host: plugins.jetbrains.com}{Accept: text/html, image/gif, image/jpeg, *; q=.2, */*; q=.2}{Connection: keep-alive}
11:09:16.506 [DEBUG] [sun.net.www.protocol.http.HttpURLConnection] sun.net.www.MessageHeader@d2006dc10 pairs: {null: HTTP/1.1 302}{Server: nginx}{Date: Mon, 03 Jul 2017 08:09:15 GMT}{Content-Length: 0}{Connection: keep-alive}{Set-Cookie: ccc=ieqpix;Max-Age=157680000;Expires=Sat, 02-Jul-2022 08:09:15 GMT}{Location: http://plugins.jetbrains.com/files/227/31087/PsiViewer.jar?updateId=31087&pluginId=227}{X-Frame-Options: DENY}{X-Content-Type-Options: nosniff}{X-XSS-Protection: 1; mode=block;}
11:09:16.506 [DEBUG] [plugin-repository-rest-client] <--- HTTP 302 http://plugins.jetbrains.com/plugin/download?pluginId=PsiViewer&version=3.28.93 (90ms)
11:09:16.506 [DEBUG] [sun.net.www.protocol.http.HttpURLConnection] sun.net.www.MessageHeader@25d24c645 pairs: {GET /files/227/31087/PsiViewer.jar?updateId=31087&pluginId=227 HTTP/1.1: null}{User-Agent: Java/1.8.0_121}{Host: plugins.jetbrains.com}{Accept: text/html, image/gif, image/jpeg, *; q=.2, */*; q=.2}{Connection: keep-alive}
11:09:16.548 [DEBUG] [sun.net.www.protocol.http.HttpURLConnection] sun.net.www.MessageHeader@15420c7610 pairs: {null: HTTP/1.1 302 Moved Temporarily}{Server: nginx}{Date: Mon, 03 Jul 2017 08:09:15 GMT}{Content-Type: text/html}{Content-Length: 154}{Connection: keep-alive}{Location: http://download.plugins.jetbrains.com/227/31087/PsiViewer.jar?updateId=31087&pluginId=227}{X-Frame-Options: DENY}{X-Content-Type-Options: nosniff}{X-XSS-Protection: 1; mode=block;}
11:09:16.548 [DEBUG] [sun.net.www.protocol.http.HttpURLConnection] Redirected from http://plugins.jetbrains.com/files/227/31087/PsiViewer.jar?updateId=31087&pluginId=227 to http://download.plugins.jetbrains.com/227/31087/PsiViewer.jar?updateId=31087&pluginId=227
11:09:16.577 [DEBUG] [sun.net.www.protocol.http.HttpURLConnection] sun.net.www.MessageHeader@25d24c645 pairs: {GET /227/31087/PsiViewer.jar?updateId=31087&pluginId=227 HTTP/1.1: null}{User-Agent: Java/1.8.0_121}{Host: download.plugins.jetbrains.com}{Accept: text/html, image/gif, image/jpeg, *; q=.2, */*; q=.2}{Connection: keep-alive}
11:09:16.608 [DEBUG] [sun.net.www.protocol.http.HttpURLConnection] sun.net.www.MessageHeader@498c0f5914 pairs: {null: HTTP/1.1 200 OK}{Content-Type: application/java-archive}{Content-Length: 94353}{Connection: keep-alive}{Date: Thu, 18 May 2017 15:09:12 GMT}{Content-Disposition: attachment; filename="PsiViewer.jar"}{Last-Modified: Wed, 17 May 2017 23:25:40 GMT}{x-amz-version-id: 59kk1y.XijZ_0aNbk7KhxwsH0ZNM.VIk}{ETag: "c7dc518b90e85b31794fd1c56bc0e981"}{Server: AmazonS3}{Age: 406}{X-Cache: Hit from cloudfront}{Via: 1.1 c49d17de779f9ba792c2761d2b2069cf.cloudfront.net (CloudFront)}{X-Amz-Cf-Id: ImgzIMO0KeCjLEnzFz4IWT5BIgp-jlEmMg45-jI3spCaPNTSbsEvxg==}
11:09:16.609 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]
11:09:16.609 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] FAILURE: Build failed with an exception.
11:09:16.609 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]
11:09:16.609 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * What went wrong:
11:09:16.610 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] A problem occurred configuring root project 'protobuf-jetbrains-plugin'.
11:09:16.610 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] > Failed to notify project evaluation listener.
11:09:16.610 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]    > The filename, directory name, or volume label syntax is incorrect
11:09:16.610 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]
11:09:16.610 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * Exception is:
11:09:16.610 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] org.gradle.api.ProjectConfigurationException: A problem occurred configuring root project 'protobuf-jetbrains-plugin'.
11:09:16.611 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.configuration.project.LifecycleProjectEvaluator.addConfigurationFailure(LifecycleProjectEvaluator.java:94)
11:09:16.611 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.configuration.project.LifecycleProjectEvaluator.notifyAfterEvaluate(LifecycleProjectEvaluator.java:89)
11:09:16.611 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.configuration.project.LifecycleProjectEvaluator.doConfigure(LifecycleProjectEvaluator.java:76)
11:09:16.611 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.configuration.project.LifecycleProjectEvaluator.access$000(LifecycleProjectEvaluator.java:33)
11:09:16.611 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.configuration.project.LifecycleProjectEvaluator$1.execute(LifecycleProjectEvaluator.java:53)
11:09:16.611 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.configuration.project.LifecycleProjectEvaluator$1.execute(LifecycleProjectEvaluator.java:50)
11:09:16.611 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.Transformers$4.transform(Transformers.java:169)
11:09:16.611 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:106)
11:09:16.611 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:61)
11:09:16.611 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.configuration.project.LifecycleProjectEvaluator.evaluate(LifecycleProjectEvaluator.java:50)
11:09:16.611 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.project.DefaultProject.evaluate(DefaultProject.java:599)
11:09:16.611 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.project.DefaultProject.evaluate(DefaultProject.java:125)
11:09:16.611 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.execution.TaskPathProjectEvaluator.configure(TaskPathProjectEvaluator.java:35)
11:09:16.611 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.execution.TaskPathProjectEvaluator.configureHierarchy(TaskPathProjectEvaluator.java:60)
11:09:16.611 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.configuration.DefaultBuildConfigurer.configure(DefaultBuildConfigurer.java:38)
11:09:16.611 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.initialization.DefaultGradleLauncher$ConfigureBuildAction.execute(DefaultGradleLauncher.java:233)
11:09:16.611 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.initialization.DefaultGradleLauncher$ConfigureBuildAction.execute(DefaultGradleLauncher.java:230)
11:09:16.612 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.Transformers$4.transform(Transformers.java:169)
11:09:16.612 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:106)
11:09:16.612 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:56)
11:09:16.612 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:160)
11:09:16.612 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:119)
11:09:16.612 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:102)
11:09:16.612 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.launcher.exec.GradleBuildController.run(GradleBuildController.java:71)
11:09:16.612 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(ExecuteBuildActionRunner.java:28)
11:09:16.612 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
11:09:16.612 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:41)
11:09:16.612 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:26)
11:09:16.612 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:75)
11:09:16.613 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:49)
11:09:16.613 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.tooling.internal.provider.ServicesSetupBuildActionExecuter.execute(ServicesSetupBuildActionExecuter.java:49)
11:09:16.613 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.tooling.internal.provider.ServicesSetupBuildActionExecuter.execute(ServicesSetupBuildActionExecuter.java:31)
11:09:16.613 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.launcher.daemon.server.exec.ExecuteBuild.doBuild(ExecuteBuild.java:67)
11:09:16.613 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
11:09:16.613 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
11:09:16.613 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.launcher.daemon.server.exec.WatchForDisconnection.execute(WatchForDisconnection.java:47)
11:09:16.613 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
11:09:16.613 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.launcher.daemon.server.exec.ResetDeprecationLogger.execute(ResetDeprecationLogger.java:26)
11:09:16.613 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
11:09:16.613 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.launcher.daemon.server.exec.RequestStopIfSingleUsedDaemon.execute(RequestStopIfSingleUsedDaemon.java:34)
11:09:16.613 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
11:09:16.613 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:74)
11:09:16.613 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:72)
11:09:16.613 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.util.Swapper.swap(Swapper.java:38)
11:09:16.614 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.launcher.daemon.server.exec.ForwardClientInput.execute(ForwardClientInput.java:72)
11:09:16.614 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
11:09:16.614 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.launcher.daemon.server.exec.LogAndCheckHealth.execute(LogAndCheckHealth.java:55)
11:09:16.614 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
11:09:16.614 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.launcher.daemon.server.exec.LogToClient.doBuild(LogToClient.java:60)
11:09:16.614 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
11:09:16.614 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
11:09:16.614 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBuild(EstablishBuildEnvironment.java:72)
11:09:16.614 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
11:09:16.614 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
11:09:16.614 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.run(StartBuildOrRespondWithBusy.java:50)
11:09:16.614 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(DaemonStateCoordinator.java:297)
11:09:16.614 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
11:09:16.614 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:46)
11:09:16.614 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Caused by: org.gradle.internal.event.ListenerNotificationException: Failed to notify project evaluation listener.
11:09:16.614 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:55)
11:09:16.614 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.event.BroadcastDispatch.dispatch(BroadcastDispatch.java:79)
11:09:16.614 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.event.BroadcastDispatch.dispatch(BroadcastDispatch.java:30)
11:09:16.614 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
11:09:16.614 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at com.sun.proxy.$Proxy16.afterEvaluate(Unknown Source)
11:09:16.614 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.configuration.project.LifecycleProjectEvaluator.notifyAfterEvaluate(LifecycleProjectEvaluator.java:82)
11:09:16.614 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   ... 56 more
11:09:16.614 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Caused by: java.io.IOException: The filename, directory name, or volume label syntax is incorrect
11:09:16.614 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.jetbrains.intellij.pluginRepository.PluginRepositoryInstance.downloadFile(pluginRepositoryRest.kt:121)
11:09:16.614 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.jetbrains.intellij.pluginRepository.PluginRepositoryInstance.download(pluginRepositoryRest.kt:80)
11:09:16.614 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.jetbrains.intellij.pluginRepository.PluginRepositoryInstance$download.call(Unknown Source)
11:09:16.614 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.jetbrains.intellij.dependency.PluginDependencyManager.downloadPlugin(PluginDependencyManager.groovy:115)
11:09:16.614 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.jetbrains.intellij.dependency.PluginDependencyManager.resolve(PluginDependencyManager.groovy:59)
11:09:16.615 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.jetbrains.intellij.dependency.PluginDependencyManager$resolve.call(Unknown Source)
11:09:16.615 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.jetbrains.intellij.IntelliJPlugin$_configurePluginDependencies_closure3.doCall(IntelliJPlugin.groovy:155)
11:09:16.615 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.jetbrains.intellij.IntelliJPlugin.configurePluginDependencies(IntelliJPlugin.groovy:138)
11:09:16.615 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.jetbrains.intellij.IntelliJPlugin.configureProjectAfterEvaluate(IntelliJPlugin.groovy:102)
11:09:16.615 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.jetbrains.intellij.IntelliJPlugin$_configureTasks_closure2.doCall(IntelliJPlugin.groovy:89)
11:09:16.615 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.listener.ClosureBackedMethodInvocationDispatch.dispatch(ClosureBackedMethodInvocationDispatch.java:40)
11:09:16.615 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.listener.ClosureBackedMethodInvocationDispatch.dispatch(ClosureBackedMethodInvocationDispatch.java:25)
11:09:16.615 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:44)
11:09:16.615 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   ... 61 more
11:09:16.615 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]
11:09:16.615 [LIFECYCLE] [org.gradle.internal.buildevents.BuildResultLogger]
11:09:16.615 [LIFECYCLE] [org.gradle.internal.buildevents.BuildResultLogger] BUILD FAILED
11:09:16.615 [LIFECYCLE] [org.gradle.internal.buildevents.BuildResultLogger]
11:09:16.615 [LIFECYCLE] [org.gradle.internal.buildevents.BuildResultLogger] Total time: 1.32 secs
```
