### ISSUE TITLE
Unable to get stub builder for io.protostuff.jetbrains.plugin.ProtoFileType

### ISSUE THREAD

**Issue by jansorg** [protostuff/protobuf-jetbrains-plugin#55]
I received this exception report through my plugin's reporter (BashSupport). A Bash plugin's call triggers the update of other files. Proto files are apparently missing a stub builder.

```java
unable to get stub builder for io.protostuff.jetbrains.plugin.ProtoFileType@6b05e369, path = /home/... stubBindingRoot = ProtoPsiFileRoot, languages = [PROTO], fileTypes = [PROTO], files = [ProtoPsiFileRoot], roots = []
java.lang.Throwable
        at com.intellij.openapi.diagnostic.Logger.error(Logger.java:132)
        at com.intellij.psi.stubs.StubProcessingHelperBase.processStubsInFile(StubProcessingHelperBase.java:81)
        at com.intellij.psi.stubs.StubProcessingHelperBase.processStubsInFile(StubProcessingHelperBase.java:52)
        at com.intellij.psi.stubs.StubIndexImpl$2.process(StubIndexImpl.java:330)
        at com.intellij.psi.stubs.StubIndexImpl$StubIdListContainerAction.perform(StubIndexImpl.java:614)
        at com.intellij.psi.stubs.StubIndexImpl$StubIdListContainerAction.perform(StubIndexImpl.java:602)
        at com.intellij.util.indexing.ValueContainer.forEach(ValueContainer.java:62)
        at com.intellij.psi.stubs.StubIndexImpl.a(StubIndexImpl.java:356)
        at com.intellij.psi.stubs.StubIndexImpl.processElements(StubIndexImpl.java:322)
        at com.intellij.psi.stubs.StubIndex.getElements(StubIndex.java:145)
        at com.intellij.psi.stubs.StubIndex.getElements(StubIndex.java:134)
        at com.ansorgit.plugins.bash.lang.psi.FileInclusionManager.findIncluders(FileInclusionManager.java:135)
        at com.ansorgit.plugins.bash.lang.psi.impl.command.SmartFunctionReference.resolveInner(SmartFunctionReference.java:69)
        at com.intellij.psi.impl.source.resolve.reference.impl.CachingReference$MyResolver.resolve(CachingReference.java:63)
        at com.intellij.psi.impl.source.resolve.reference.impl.CachingReference$MyResolver.resolve(CachingReference.java:58)
        at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:140)
        at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:205)
        at com.intellij.psi.impl.source.resolve.reference.impl.CachingReference.resolve(CachingReference.java:33)
        at com.ansorgit.plugins.bash.lang.psi.impl.command.AbstractBashCommand.isFunctionCall(AbstractBashCommand.java:103)
        at com.ansorgit.plugins.bash.editor.annotator.BashAnnotator.annotateCommand(BashAnnotator.java:196)
        at com.ansorgit.plugins.bash.editor.annotator.BashAnnotator.annotate(BashAnnotator.java:76)
        at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.a(DefaultHighlightVisitor.java:139)
        at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.visit(DefaultHighlightVisitor.java:102)
       ...
```

**Comment by kshchepanovskyi** [comment]
Thank you for reporting this, I will try to fix it as soon as possible.

**Comment by kshchepanovskyi** [comment]
As far as I understand, custom language support plugins are not required to implement stubs. It is recommendation, not a requirement (however, I'm planning to use stubs eventually, but not right now).

http://www.jetbrains.org/intellij/sdk/docs/basics/indexing_and_psi_stubs.html

> Querying a stub index gets you the set of matching PSI elements. Therefore, custom language plugin developers **should** typically use stub indexes in their plugin implementations.

Most likely same issue might happen with any other file type.

It looks like the root cause of issue is in `StubIndex.getElements(...)` - it should not throw exceptions in cases like this one. If some plugin does not support stub index - it should just ignore that type of files.

About a fix. This is the part of code that is mentioned in the stacktrace - 
https://github.com/jansorg/BashSupport/blob/idea/172.x/src/com/ansorgit/plugins/bash/lang/psi/FileInclusionManager.java#L135 :

```java
GlobalSearchScope searchScope = BashSearchScopes.moduleScope(file);
// ...
Collection<BashIncludeCommand> includeCommands = StubIndex.getElements(BashIncludedFilenamesIndex.KEY, filename, project, searchScope, BashIncludeCommand.class);
```

Plugin tries to find `BashIncludeCommand` globally, in all file types.
I think the easiest way to fix an issue is to change `BashSearchScopes.moduleScope(file)` to `BashSearchScopes.bashOnly(BashSearchScopes.moduleScope(file))`.

@jansorg - please let me know if it is acceptable (I can make PR, it's really small - however, I cannot figure out to which branch - there are many).

**Comment by jansorg** [comment]
@kshchepanovskyi Thanks for the feedback. I'll have a look at the BashSupport code, at first glance it seems that your suggestion should work.
IntelliJ seems to throw the exception where it's not supposed to.

**Comment by jansorg** [comment]
@kshchepanovskyi This will be fixed with the next update by https://github.com/jansorg/BashSupport/issues/451
Thank you for your help!

(It might happen that someone include a plain text file or another file not marked as Bash. In that case file navigation will break but this fix is better than causing exceptions all over the place)
