### ISSUE TITLE
IllegalArgumentException: Argument for @NotNull parameter 'element' of io/protostuff/jetbrains/plugin/view/structure/Abstra...

### ISSUE THREAD

**Issue by kshchepanovskyi** [protostuff/protobuf-jetbrains-plugin#74]
https://sentry.io/ks-projects/protobuf-support/issues/323626184/

```
IllegalArgumentException: Argument for @NotNull parameter 'element' of io/protostuff/jetbrains/plugin/view/structure/AbstractTreeElement.<init> must not be null
    at io.protostuff.jetbrains.plugin.view.structure.AbstractTreeElement.$$$reportNull$$$0(AbstractTreeElement.java)
    at io.protostuff.jetbrains.plugin.view.structure.AbstractTreeElement.<init>(AbstractTreeElement.java)
    at io.protostuff.jetbrains.plugin.view.structure.RootTreeElement.<init>(RootTreeElement.java:22)
    at io.protostuff.jetbrains.plugin.view.structure.ProtoStructureViewModel.getProtoRootElement(ProtoStructureViewModel.java:33)
    at io.protostuff.jetbrains.plugin.view.structure.ProtoStructureViewModel.<init>(ProtoStructureViewModel.java:28)
...
(34 additional frame(s) were not displayed)

Argument for @NotNull parameter 'element' of io/protostuff/jetbrains/plugin/view/structure/AbstractTreeElement.<init> must not be null
```

**Comment by kshchepanovskyi** [comment]
Cannot reproduce in IntelliJ IDEA 2018.2.
